apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarea-deployment
  labels:
    app: micro-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-java
  template:
    metadata:
      labels:
        app: micro-java
    spec:
      containers:
      - name: micro-java
        image: dsarmientoparra/microservicio-java:latest
        ports:
        - containerPort: 8080